# My Variables
@contentType = application/json
@baseurl = http://localhost:3001/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbWkiLCJpZCI6IjYzOTVjOTg1NDMxMjkyZDc2NGNmZTE0MCIsImlhdCI6MTY3MDc3MzE2NX0.bav3HejTwXp5dpwyimgd140ckyWN5WOcejUpLOyH-ig

### login
POST  {{baseurl}}/login
Content-Type: {{contentType}}

{
    "username": "sami",
    "password": "salainen"
}

### POST Request
POST {{baseurl}}/notes
Content-Type: {{contentType}}
Authorization: bearer {{token}}

{
        "content": "Note 78",
        "important": true
}

### GET Request
GET {{baseurl}}/notes
Content-Type: {{contentType}}
Authorization: bearer {{token}}

### GET Request
GET {{baseurl}}/notes/6395cd6ca70ce7abb28c6407
Content-Type: {{contentType}}
Authorization: bearer {{token}}

### PUT  Request
PUT {{baseurl}}/notes/6395c5399d8d1485f6a4e187
Content-Type: {{contentType}}
Authorization: bearer {{token}}

{
        "content": "Note 77",
        "important": true
}

### Signup
POST  {{baseurl}}/users
Content-Type: {{contentType}}

{
      "username": "sami",
      "name": "Sami",
      "password": "salainen"
}

### Signup
POST  {{baseurl}}/users
Content-Type: {{contentType}}

{
      "username": "mluukkai",
      "name": "Matti Luukkainen",
      "password": "salainen"
}


### reset database
POST {{baseurl}}/testing/reset
Content-Type: {{contentType}}

